# Generated by Django 2.1.5 on 2019-11-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webproject',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
