# Generated by Django 2.1.5 on 2019-11-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprojectapp', '0002_webproject_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webproject',
            name='offer',
        ),
    ]
